### ISSUE TITLE
Public docker image hosting

### ISSUE THREAD

**Issue by sptfinderl** [authcrunch/authcrunch#2]
Hello,

First of all thanks for your work on these very useful packages.

I see that a Github action is publishing images to ghcr.io
However the images seems to be private, as trying to pull `ghcr.io/authcrunch/authcrunch:latest` returns a "denied" error.

Did you considered having this image available for download by everyone ?

Thx

**Comment by greenpau** [comment]
@sptfinderl , thank you for raising it. Do you know the steps to make package available to everyone? I was doing housekeeping and moved repo over to authcrunch org. Broke it. 

This should be available to everyone.

**Comment by sptfinderl** [comment]
I had not looked at this commit previously. Indeed the situation is a bit strange as :

* Pulling the image `authp/authp` works.
* Navigating on ghcr.io/authp/authp redirects on the Authp org packages page 

but

* Navigating on ghcr.io/authcrunch/authcrunch fails
* The "package" section in `authcrunch/authcrunch` show "1" in the badge, but nothing in the list
* The image (beta at least) seems to be pushed correctly as per [the action](https://github.com/authcrunch/authcrunch/actions/runs/8352691996/job/22863185924#step:8:199)

Maybe the packages are disabled or set as private for the Authcrunch org on Github ? Or for `authcrunch/authcrunch` ?

**Comment by greenpau** [comment]
@sptfinderl . the `authp/authp` is no longer the one you should be pulling from.

> The image (beta at least) seems to be pushed correctly as per [the action](https://github.com/authcrunch/authcrunch/actions/runs/8352691996/job/22863185924#step:8:199)

Are you able to pull the `beta`?

**Comment by greenpau** [comment]
@sptfinderl , I found the issue. The package was marked as private. I changed it to `public` and releasing the new version with the changes listed here: https://github.com/greenpau/caddy-security/issues/327

**Comment by sptfinderl** [comment]
I confirm the issue is fixed, thanks !
