### ISSUE TITLE
Updating from old authp-image

### ISSUE THREAD

**Issue by Hoempi** [authcrunch/authcrunch#3]
In the other issue linked below you mentionend that the authp image is outdated and should not be used anymore.

Will I be able to just replace the image in my docker-compose file, or are there any breaking changes which I need to attend to first?

              @sptfinderl . the `authp/authp` is no longer the one you should be pulling from.

> The image (beta at least) seems to be pushed correctly as per [the action](https://github.com/authcrunch/authcrunch/actions/runs/8352691996/job/22863185924#step:8:199)

Are you able to pull the `beta`?

_Originally posted by @greenpau in https://github.com/authcrunch/authcrunch/issues/2#issuecomment-2016912687_

**Comment by greenpau** [comment]
@Hoempi , moved it to github.com/authcrunch/authcrunch package

**Comment by greenpau** [comment]
Replace as is. All stayed the same.

**Comment by Hoempi** [comment]
Thanks a lot!
