### ISSUE TITLE
docker example/usage

### ISSUE THREAD

**Issue by EatPrilosec** [authcrunch/authcrunch#4]
difficult to figure out things like where to mount persistent config/caddyfile etc. its not very clear how to use this docker image.

after further inspection of the repo, it seems like its using the official caddy docker as a base, so my plan is to try their docs for the docker setup, but that could be made more clear in the readme if thats the case. just a suggestion :)

**Comment by greenpau** [comment]
@EatPrilosec , your question is really how I use caddy with Docker. This plugin is no different than any other plugins. I suggest you visit caddy community forum or checkout this plugin https://github.com/lucaslorentz/caddy-docker-proxy

It has examples of how go use docker with caddy.

**Comment by greenpau** [comment]
@EatPrilosec  , this article has reference to the mapping of volumes you need to have. https://medium.com/@fish_underlings/struggling-with-caddy-docker-proxy-2936f9256a79
