### ISSUE TITLE
Missing basic theme templates from go-authcrunch

### ISSUE THREAD

**Issue by ptrsny** [authcrunch/authcrunch#5]
When I start the container with a Caddyfile that uses a `ldap identity store` with authentication portal and authorization policy set up like described by the [example](https://github.com/authcrunch/authcrunch.github.io/blob/main/assets/conf/ldap/Caddyfile) and [documentation](https://docs.authcrunch.com/docs/authenticate/ldap/ldap). I do not get any login form.

Checking the contents of the container shows that there are not `*.template` files present.

I assume this is because the assets from go-authcrunch are not copied into the container?!

Tested with:
- Ubuntu 22.04
- docker.io 24.0.7-ubuntu2~22.04.1
- authcrunch container v1.0.11

**Comment by greenpau** [comment]
> I assume this is because the assets from go-authcrunch are not copied into the container?!

@ptrsny , yes, they are not copied. You need to copy them from [here ](https://github.com/greenpau/go-authcrunch/tree/main/assets/portal/templates/basic) and modify to your liking.

You can see how I do it for my project here: https://github.com/greenpau/caddy-security/issues/353

Specifically, 

```
				static_asset "assets/images/bizdevstack_banner.jpg" "images/jpg" ui/banner.jpg
				static_asset "assets/images/bizdevstack_logo.png" "images/png" ui/logo.png
				static_asset "assets/images/favicon.png" "images/png" ui/favicon.png
				template login ui/login.template
				template sandbox ui/sandbox.template
				template portal ui/portal.template
				template whoami ui/whoami.template
```
